name: FrontVue CI

on:
  push:
    branches: [ frontend ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: cd ahp-form && npm i
    - run: cd ahp-form && npm run build
    - run: cp -f dist/ /var/www/html/.