name: Deploy2 Api App

on:
  push:
    branches: [main]


jobs:
 build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [15.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: cd ahp-api && npm i
    - run: echo `pwd`
    - run: cd ahp-api && npm run build
    - run: cd ahp-api && cp /home/ubuntu/configEnvs/back/.env .
    - run: cd ahp-api && pm2 restart ApiBackend