name: Deploy Frontend and Backend

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: cd ahp-form && npm i
    - run: cd ahp-form && cp /home/ubuntu/configEnvs/front/.env .
    - run: cd ahp-form && npm run build
    - run: cd ahp-form && cp -r dist/* /var/www/html/
    - run: cd ahp-api ; echo `pwd`; cp /home/ubuntu/configEnvs/back/.env .
    - run: cd ahp-api ; echo `pwd`; npm i; npm run build
    - run: cd ahp-api && pm2 restart ApiBackend